stages:
  - build

# build_mac:
#   stage: build
#   tags:
#     - ios
#   before_script:
#     - bash ./ci/scripts/prepare.sh
#   script: 
#     - bash ./ci/scripts/build_all.sh
#   only:
#     - merge_requests

build_linux:
  stage: build
  image: ubuntu:latest
  tags:
    - docker
  before_script:
    - apt-get update
    - apt-get -y install curl cmake ninja-build
    - bash ./ci/scripts/prepare.sh
  script: 
    - bash ./ci/scripts/build_all.sh
  only:
    - merge_requests