stages:
  - build

build_mac:
  stage: build
  tags:
    - xcode-11.3
  before_script:
    - bash ./ci/scripts/prepare.sh
  script: 
    - bash ./ci/scripts/build_all.sh 15.3.0
  only:
    - merge_requests

build_linux:
  stage: build
  image: ubuntu:20.04
  tags:
    - docker
  before_script:
    - apt-get update
    - ln -fs /usr/share/zoneinfo/Europe/Warsaw /etc/localtime
    - apt-get -y install curl cmake ninja-build unzip tar python3-pip
    - bash ./ci/scripts/prepare.sh
  script: 
    - bash ./ci/scripts/build_all.sh 15.3.0
  only:
    - merge_requests