name: Github CI configuration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get -y install curl cmake ninja-build unzip tar python3.7 python3-pip python3-venv git
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1
          python3 --version
      - name: Prepare repository
        run: ./ci/scripts/prepare.sh
      - name: Run Python tests
        run: ./ci/scripts/run_tests.sh
      - name: Generate CMake files
        run: ./ci/scripts/generate_cmake.sh
      - name: Generate CMake libraries tests
        run: ./ci/scripts/generate_cmake_tests.sh
      - name: Build all libraries tests
        run: ./ci/scripts/build_all_libraries.sh
      - name: Build all examples
        run: ./ci/scripts/build_all_examples.sh
